console.log(3 + 2)
console.log(3 - 2)
console.log(3 * 2)
console.log(3 / 2)
console.log(3 % 2)
console.log('Hello ' + 'World')
console.log('My ' + 'name ' + 'is ' + 'Nika')
console.log("I live in Tbilisi")
console.log('JavaScript'.length)
console.log('JavaScript'.toUpperCase())
console.log('JAVASCRIPT'.toLowerCase())
console.log("      Hello      ".trim())
console.log('Programming'.startsWith('P'))
console.log('Programming'.slice(0, 4))
console.log('JavaScript'.slice(6,))
console.log((("      JavaScript      ".trim()).toUpperCase()).length)
// long ones
console.log("Programming".slice(0, 7))
console.log((("Programming".slice(0, 7)).toLowerCase()))
console.log((("Programming".slice(0, 7)).toLowerCase()).length)
//
console.log("      JavaScript      ".trim())
console.log(("      JavaScript      ".trim()).startsWith('Java'))
console.log((("      JavaScript      ".trim()).slice(0,4)).toUpperCase())
console.log((("      JavaScript      ".trim()).slice(0,4)).toUpperCase().length)
console.log('Languege: ' + (("      JavaScript      ".trim()).slice(0,4)).toUpperCase())
